# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c3ffb43e55f7a8c8d617cc59bb78c32ab7f5c7b78fe55b4b79e9906b38f8665df74b683d3e7937795b5beb640c0f7d2f893a1b21e62d508e729dab6c57c36657

test:
  secret_key_base: 841d55e5e196b08f5745575851f2da92da330d545ff217cb022fe6f260a65f3ba59d21c82bbc7a93e547aa980785b92e4e0efd2e683c62a4192f2d835c0a6ebc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
